### ISSUE TITLE
검색 시 목록 보기 요청

### ISSUE THREAD

**Issue by dacodaco** [Neph3779/BuyOrNot#1]
예를 들어 로지텍으로 검색했을 때,
로지텍의 제품들이 목록화되어 그 중 한 가지를 선택할 뷰 레이어가 하나 있었으면 좋겠습니다.

지금은 로지텍으로 검색하면 k380으로 바로 들어가버리네요 ㅜ

**Comment by sero3779** [comment]
<img src="https://user-images.githubusercontent.com/67148595/178447415-40ee5ac6-dff7-45cb-93d5-89c3362f1fc2.png" width=50% height=50%>

반영되었고 곧 업데이트 예정입니다~ 👍
